Implement pipeline pattern
eclipse-velocitas/velocitas-project-generator-npm pull request #7
Opened 2022-11-15 16:08 UTC by dennismeister93

Signed-off-by: Dennis Meister <dennis.meister@bosch.com>

Implement pipeline pattern for extracting needed code snippet blocks

2022-11-19 11:52 UTC, doosuu reviewed
Logger statements are missing f-strings, look at example_output_1.py line 91

2022-11-19 11:52 UTC, doosuu commented on src/code-formatter.ts
> +    private codeContext: CodeContext = {
Is this explicit initialization needed? We already have empty defaults in the class.

2022-11-19 11:52 UTC, doosuu commented on src/code-formatter.ts
> +import { ExtractClassesStep } from './pipeline/extract-classes';
Finding shall be a file wide finding, ignore the line it is attached to:
`code-foramtter.ts`: File is not a formatter, it is a converter

2022-11-19 11:52 UTC, doosuu commented on src/code-formatter.ts
>          let decodedBase64CodeSnippet = Buffer.from(base64CodeSnippet, CONTENT_ENCODINGS.base64 as BufferEncoding).toString(
Decoding of the base64 string should be done outside of the method. It is a separate concern.

2022-11-19 11:52 UTC, doosuu commented on src/code-formatter.ts
>          let decodedMainPyContentData = Buffer.from(base64MainPyContentData, CONTENT_ENCODINGS.base64 as BufferEncoding).toString(
Decoding could be done outside the method, it is a seperate concern

2022-11-19 11:52 UTC, doosuu commented on src/code-formatter.ts
>          const encodedNewMainPy = Buffer.from(formattedFinalCode, CONTENT_ENCODINGS.utf8 as BufferEncoding).toString(
Encoding should be done outside of the method, it is a seperate concern

2022-11-19 11:52 UTC, doosuu commented on src/code-formatter.ts
>      public formatMainPy(base64MainPyContentData: string, base64CodeSnippet: string, appName: string): string {
Add method documentation.

2022-11-19 11:52 UTC, doosuu commented on src/code-formatter.ts
> +    private adaptCodeSnippet(base64CodeSnippet: string): void {
Ignore the line this finding is attached to. The utility methods above this one like indent, createArray..., createMultiline should be moved to a utils file to have this file as short and concise as possible.

2022-11-19 11:52 UTC, doosuu commented on src/pipeline/prepare-code-snippet.ts
> +export class PrepareCodeSnippetStep extends PipelineStep {
Add missing class documentation. What does this pipeline step do?

2022-11-19 11:52 UTC, doosuu commented on src/pipeline/prepare-code-snippet.ts
> +    private removeSubstringFromArray(array: string[], substringOne: string, substringTwo?: string): string[] {
If this removes a substring from an array why are there 2 substrings possible as parameters? Should this be named removeSubstring**s**FromArray ?

2022-11-19 11:52 UTC, doosuu commented on src/pipeline/pipeline-base.ts
> +    indentCodeSnippet(decodedSnippet: string, indentCount: number): string {
This method already exists in code-foramter.ts

2022-11-19 11:52 UTC, doosuu commented on src/pipeline/pipeline-base.ts
> +    createMultilineStringFromArray(array: string[] | string[][]): string {
This method already exists in code-foramter.ts

2022-11-19 11:52 UTC, doosuu commented on src/pipeline/pipeline-base.ts
> +export class PipelineStep implements IPipelineStep {
Why is there a base implementation of the interface? Add a class documentation.

2022-11-19 11:52 UTC, doosuu commented on src/pipeline/extract-variables.ts
> +export class ExtractVariablesStep extends PipelineStep {
Add missing class documentation. What does this pipeline step do?

2022-11-19 11:52 UTC, doosuu commented on src/pipeline/extract-methods.ts
> +export class ExtractMethodsStep extends PipelineStep {
Add missing class documentation. What does this pipeline step do?

2022-11-19 11:52 UTC, doosuu commented on src/pipeline/extract-imports.ts
> +export class ExtractImportsStep extends PipelineStep {
Add missing class documentation. What does this pipeline step do?

2022-11-19 11:52 UTC, doosuu commented on src/pipeline/extract-classes.ts
> +export class ExtractClassesStep extends PipelineStep {
Add missing class documentation. What does this pipeline step do?

2022-11-19 11:52 UTC, doosuu commented on src/pipeline/create-code-snippet.ts
> +export class CreateCodeSnippetForTemplateStep extends PipelineStep {
Add missing class documentation. What does this pipeline step do?

2022-11-19 11:54 UTC, doosuu requested changes
Please have a look at the findings.

2022-11-20 09:37 UTC, dennismeister93 commented
> Logger statements are missing f-strings, look at example_output_1.py line 91

Hi @doosuu 
Unfortunately our linter has problems with using this. 
"Use lazy % formatting in logging functionspylint(logging-fstring-interpolation)"
I would propose we do not change it within this PR

2022-11-21 11:59 UTC, doosuu approved these changes
LGTM

2022-11-21 12:00 UTC, merged